# Generated by Django 4.2.3 on 2023-07-25 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
